project:
  type: website

website:
  title: "DOPS Demo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: analisis.qmd
        text: Análisis
      - href: guia-docente.qmd
        text: Guía Docente
      - href: guia-estudiante.qmd
        text: Guía Estudiante
      - href: about.qmd
        text: Acerca del proyecto

format:
  html:
    lang: es
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true